EXTENSION_TARGET = meme-smileys.oex
MEME_IMAGES = img/*.png
DIST_FILES = config.xml icon.png includes/base.js includes/defaultSmileyTable.js includes/smileyParser.js includes/replace.js index.html options.html

all: includes/defaultSmileyTable.js

includes/defaultSmileyTable.js: defaultSmileyTable.js-source $(MEME_IMAGES)
	echo "// Autogenerated file, do not modify\nvar img = {" >$@
	for i in $(MEME_IMAGES); do \
		IMGDIMEN=`identify $$i`; \
		echo -n "  `basename $$i .png`: {\n    imageDataBase64: '" >>$@; \
		base64 -w 0 $$i >>$@; \
		echo "',\n    height: `echo $$IMGDIMEN | sed -e 's/.* PNG [0-9]*x//' -e 's/ .*//'`," >>$@; \
		echo "    width: `echo $$IMGDIMEN | sed -e 's/.* PNG //' -e 's/x.*//'`" >>$@; \
		echo "  }," >>$@; \
	done
	# This is to avoid a trailing comma at the end of the last image
	echo "  fakeImage: {}\n};\n" >>$@
	cat defaultSmileyTable.js-source >>$@

dist: all $(EXTENSION_TARGET)

$(EXTENSION_TARGET): $(DIST_FILES)
	zip -9r $(EXTENSION_TARGET) $(DIST_FILES)
